name: Regenerate dalamudrepo.json
on: 
  workflow_dispatch:
  push:
    branches:
    - master
jobs:
  generate:
    name: Regenerate dalamudrepo.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
            python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - uses: actions/checkout@v2
      - name: Generate dalamudrepo.json
        run: python ffxiv/update.py
      - uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub Action
          author_email: github-actions[bot]@users.noreply.github.com
          message: Regenerate dalamudrepo.json